### ISSUE TITLE
Multiple Video In a List is Causing an Issue

### ISSUE THREAD

**Issue by JolChrSA** [wxxsw/VideoPlayer#11]
I am using VideoPlayer in List, but the issue I am facing is that first One or Two videos playing correctly, but after I scrolling List View the remaining video did not play properly.
         Please Help me for that. Thanks in Advance.

**Comment by wxxsw** [comment]
I think the complicated thing is to observe the scrolling in the List and then play the appropriate video.

I think it may be necessary to use the `preference` API to get the position of the player in the scroll, and then change the state of the player after calculation.

**Comment by JolChrSA** [comment]
Ok, Got it . Thanks bro for your help .
