### ISSUE TITLE
Quick start not playing

### ISSUE THREAD

**Issue by jclaude33** [wxxsw/VideoPlayer#12]
*Used swift package to create dependency

*included the following:
import AVFoundation
import SwiftUI
import VideoPlayer
 import UIKit

added to plist:
App Transport Security Settings
-- Allow Arbitrary Loads
-- Allow Arbitrary Loads for Media
-- AllowArbitrary Loads for Web Content

However, it is still not playing.  Please help

**Comment by wxxsw** [comment]
You can try to start with Demo, change the video URL first, and then bring it to your project step by step.

In addition to VideoPlayer having its own Demo, I have another github project that also uses VideoPlayer.

https://github.com/wxxsw/SwiftUI-WeChat
