### ISSUE TITLE
Error when app is closed

### ISSUE THREAD

**Issue by ebby** [wxxsw/VideoPlayer#13]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'An instance of AVPlayer cannot remove a time observer that was added by a different instance of AVPlayer.'

**Comment by Bubba8291** [comment]
I'm having the same issue, any luck getting it to work?

**Comment by onurkun** [comment]
VideoPlayer.swift 

31.line => `@Binding private(set) var url: String`
43.line => `init function public init(url: Binding<String>, play: Binding<Bool>, time: Binding<CMTime> = .constant(.zero)) {
        _url = url
        _play = play
        _time = time
    }`
177.line => ` play ? uiView.play(for: URL(string: url)!) : uiView.pause(reason: .userInteraction)`

After making these adjustments, you can make any changes with the timer, you will get rid of this error.

`Timer.scheduledTimer(withTimeInterval: 0.01, repeats: false)`

**Comment by wxxsw** [comment]
Fixed in tag [1.1.7](https://github.com/wxxsw/VideoPlayer/tree/1.1.7)
