### ISSUE TITLE
哪里可以设置进度条和全屏啊？

### ISSUE THREAD

**Issue by badaozhai** [wxxsw/VideoPlayer#15]
哪里可以设置进度条和全屏啊？

**Comment by wxxsw** [comment]
此框架提供的是纯播放器，但是提供各种回调，你可以通过例如 ZStack 叠加控制层，来增加进度条和全屏按钮，通过 VideoPlayer 的 Binder 或者回调更新进度条等

**Comment by badaozhai** [comment]
多谢多谢
