### ISSUE TITLE
GSPlayer compilation error on Version 12.0 (12A7208)

### ISSUE THREAD

**Issue by daihovey** [wxxsw/VideoPlayer#16]
Cant run VideoPlayer with iOS 14 using Version 12.0 (12A7208)
`Method cannot be in an @objc extension of a class (without @nonobjc) because the type of the parameter 1 cannot be represented in Objective-C`
on 
```    /// Requests invocation of a block when specified times are traversed during normal playback.
    @discardableResult
    open func addBoundaryTimeObserver(forTimes times: [CMTime], queue: DispatchQueue? = nil, using: @escaping () -> Void) -> Any? {
        return player?.addBoundaryTimeObserver(forTimes: times.map { NSValue(time: $0) }, queue: queue, using: using)
    }
```
 method in `VideoPlayerView.swift`

**Comment by daihovey** [comment]
@wxxsw Why did you close the issue?

**Comment by wxxsw** [comment]
Hello, I have fixed this error, you can update to the latest version.
