### ISSUE TITLE
crash when load next video

### ISSUE THREAD

**Issue by foolbear** [wxxsw/VideoPlayer#17]
Crash will not present if stop video playing before switching next video. But I want auto play when swipe to new video, just like tiktok.

crash log:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'An instance of AVPlayer cannot remove a time observer that was added by a different instance of AVPlayer.'

source code:
`struct ContentView: View {
    @State private var index = 0
    @State private var play: Bool = true
    var manager: Manager { return Manager.shared }
    var count: Int { return manager.datas.count }
    var data: MyData { return manager.datas[index] }
    var url: URL? { return URL(string: data.url) }
    
    var body: some View {
        ZStack {
            Rectangle().fill().foregroundColor(.black)
            url.map { VideoPlayer(url: $0, play: $play) }
        }
        .gesture(DragGesture(minimumDistance: 0, coordinateSpace: .local)
                    .onEnded({ value in
                        if value.translation.height < 0, index < count - 1 {
                            index += 1
                        }
                        if value.translation.height > 0, index > 0 {
                            index -= 1
                        }
                    }))
        .ignoresSafeArea()
    }
}`

**Comment by EnesKaraosman** [comment]
@foolbear any progress? I've the same issue.

**Comment by yueyueyaofaguang** [comment]
> @foolbear If I put some time between video switchings it works, you found any other solution/workaround?

Can you give an example for this Solution？Thank you!

**Comment by yueyueyaofaguang** [comment]
> @foolbear If I put some time between video switchings it works, you found any other solution/workaround?
Can you give an example for this Solution？Thank you!

**Comment by yueyueyaofaguang** [comment]
> > > @foolbear If I put some time between video switchings it works, you found any other solution/workaround?
> > > Can you give an example for this Solution？Thank you!
> 
> I basically switched to next video in a delayed main thread closure like below;
> 
> ```swift
> DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) {
>    // This might be your Next Video Button's action!
> }
> ```



> > > @foolbear If I put some time between video switchings it works, you found any other solution/workaround?
> > > Can you give an example for this Solution？Thank you!
> 
> I basically switched to next video in a delayed main thread closure like below;
> 
> ```swift
> DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) {
>    // This might be your Next Video Button's action!
> }
> ```

It solve my question.Thanks you for your answer.

**Comment by GustasBr** [comment]
I have the same problem and the solution didn't work. So, at the beginning I have initial `videoURL`. Then when user press the button another video in 5-7 sec. comes up. But my app crashes because of the same error like you have. I tried to use delayed main thread closure like you suggested when using it in the button where user changes videoURL but still the same issue.

Code:

`VideoPlayer(url: videoURL!, play: $play)`
                `.autoReplay(true)`


`Button(action: {`                
                `setup(url: videoURL!, width: abs(size.width), height: abs(size.height)) // This function basically change video contrast and sets a new videoURL.`
            `}) {`
                `Text("Change Video")`
           ` }`

**Comment by wxxsw** [comment]
I fixed the problem, added a "Next Video" button to the Demo, and tested it, and it will no longer crash. (DispatchQueue.main.asyncAfter is no longer needed)
