### ISSUE TITLE
This Media Format is Not Supported (.mov file)

### ISSUE THREAD

**Issue by realjpro** [wxxsw/VideoPlayer#19]
@wxxsw  Hi there - I'm getting this error:
`Error Error Domain=AVFoundationErrorDomain Code=-11828 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x281bd39c0 {Error Domain=NSOSStatusErrorDomain Code=-12847 "(null)"}}`

trying to play a file like this: https://f000.backblazeb2.com/file/lighthouseStories/641FoyZcKFbHiD1Ceks4-snippet

This file URL works just fine with the standard AVPlayer, not sure why I'm getting this error. Please advise.

**Comment by realjpro** [comment]
Update: I did get it to work by appending the file type to the URL. Now, the issue is it's not showing up on my view, and the play/pause is happening every second rather than after the entire duration of the video (0:03). Here's my code in the view body:

`VideoPlayer(url: URL(string:"https://f000.backblazeb2.com/file/lighthouseStories/KevinHartSnippet.mov")!, play: .constant(true))
//                    .mute(true)
//                    .autoReplay(true)
//                    .onStateChanged { state in
//                                    switch state {
//                                    case .loading:
//                                        // Loading...
//                                        print("Loading")
//                                    case .playing(let totalDuration):
//                                        // Playing...
//                                        print("Playing")
//                                    case .paused(let playProgress, let bufferProgress):
//                                        // Paused...
//                                        print("Paused")
//                                    case .error(let error):
//                                        // Error...
//                                        print("Error \(error.debugDescription)")
//                                    }
//                                }
//                    .frame(width: geometry.size.width, height: geometry.size.height)
//                    .scaledToFill()
`

**Comment by wxxsw** [comment]
I use Example to play the link you gave, and it can be played normally.

You can have a try.

**Comment by vitruvvius** [comment]
#if !os(macOS)
            guard
                let mimeType = response.mimeType,
                mimeType.contains("video/")
        else { completionHandler(.cancel); print("error_mimeType"); return }
        #endif
        
happens here
