### ISSUE TITLE
Add http headers while accessing the video resources?

### ISSUE THREAD

**Issue by czf0613** [wxxsw/VideoPlayer#21]
A nice project, but I was wondering how can I add a http header while requesting the video, since I have to check the "token" while the user is trying to fetch that resources. Thanks a lot!

**Comment by wxxsw** [comment]
Add
```swift
VideoPlayer.customHTTPHeaderFields { url in
    // generate url token
    return token // return [String : String]?
}
```

**Comment by czf0613** [comment]
Thanks a million!

**Comment by X901** [comment]
> Add
> 
> ```swift
> VideoPlayer.customHTTPHeaderFields { url in
>     // generate url token
>     return ["token": token] // return [String : String]?
> }
> ```

where should I use token , 
I try add it onApear but it doesn't work

**Comment by X901** [comment]
@wxxsw  could you give as a example code ?
