### ISSUE TITLE
Cocoa is not available when building for iOS.

### ISSUE THREAD

**Issue by MarsXan** [wxxsw/VideoPlayer#22]
**Cocoa is not available when building for iOS. Consider using `#if !os(iOS)` to conditionally import this framework.**

when I want to build my app I got this error in GSAVPlayerViewController class.

it was ok on 1.1.6 but after updating to the latest version got this error.
my Xcode version: 12.2

**Comment by wxxsw** [comment]
It has been fixed and version 1.2.2 has been released.
