### ISSUE TITLE
Header Range issue

### ISSUE THREAD

**Issue by IvanShah** [wxxsw/VideoPlayer#23]
Sometimes server returns error 416. I suppose this happens because of wrong range header if preload byte count more then file size. Header when error occurs is Range = "bytes=170636-2097151". First index is more then file size too. When header is "bytes=0-2097151" server returns 0 - 170635 with 206 code after that framework make request with out of bounds range "bytes=170636-2097151" but I think it should be "bytes=170635-170636"

Preconditions: server Amazon CDN, file size = 170636, preloadByteCount = 2097152

**Comment by wxxsw** [comment]
Now the preload does not check the actual size of the video, only downloads according to the preset preload size. If I have time, I will try to optimize this.

If you want to avoid this error for now, you can either reduce the preload size or decide not to put the preload in if the video is too small.

**Comment by IvanShah** [comment]
I think it can be just wrong first index if header is "bytes=170635-2097151" it works

**Comment by wxxsw** [comment]
Sorry, I see what you mean now.

**Comment by wxxsw** [comment]
I guess it's because when you called preload, the video was already in the local cache, and the size was 170635, so the first index was 170635. Is that right?

**Comment by wxxsw** [comment]
I'll try to fix it.

**Comment by IvanShah** [comment]
It happens in really rare case so unfortunately I don't know is it was in local cache or not:(

**Comment by wxxsw** [comment]
It has been fixed and released as version 1.2.3, so you can see if your problem is fixed.

**Comment by IvanShah** [comment]
Thank you!
