### ISSUE TITLE
支持m3u8和rtmp格式吗

### ISSUE THREAD

**Issue by wangjunjx8868** [wxxsw/VideoPlayer#25]

**Comment by wxxsw** [comment]
不支持的，目前只支持 mp4

**Comment by wxxsw** [comment]
确切的说是，可以播放 m3u8（但没有边下边播），不可以播放 rtmp

**Comment by wangjunjx8868** [comment]
我测试了直播情况下的m3u8 貌似不行

**Comment by wxxsw** [comment]
了解了，目前这个仓库只支持 MP4，因为如果要支持 m3u8 和 rtmp 需要完全不同的实现方法，暂时没有支持的计划
