### ISSUE TITLE
bug:Demo项目播放中的时候切下一个视频播放进度会出问题

### ISSUE THREAD

**Issue by WanderROS** [wxxsw/VideoPlayer#34]
初学SwiftUI，很高兴看到作者的项目，Demo程序正在播放视频的时候切下一个视频的时候，会导致 @State private var time: CMTime = .zero 跳变，并且暂停的时候还会持续增加。

**Comment by wxxsw** [comment]
我测了一下暂停的时候没有持续增加，不过切视频的时候，还是会多输出一次上个视频的时间点（fixed）。
