### ISSUE TITLE
已经无法使用

### ISSUE THREAD

**Issue by underthestars-zhy** [wxxsw/VideoPlayer#35]
![Simulator Screen Shot - iPhone 11 Pro - 2021-12-13 at 08 53 55](https://user-images.githubusercontent.com/46642225/145737021-eafbaccb-8fd1-480e-ad38-03ae31f6c36e.png)

**Comment by wxxsw** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/921863/145744220-35b20b3e-4042-4f5c-9889-5c5978749329.png">
我试了下可以，我看了下，第一个视频需要翻墙，你可以点击 NextVideo 看下其它视频

**Comment by underthestars-zhy** [comment]
翻墙了也不行

**Comment by underthestars-zhy** [comment]
是iOS15吗

**Comment by wxxsw** [comment]
我是 iOS 15，你是在 Demo 工程中试的吗？如果你是在新工程试的话，不要忘记设置 ATS

**Comment by underthestars-zhy** [comment]
ATS如何设置

**Comment by wxxsw** [comment]
https://www.jianshu.com/p/bc9792f86850
