### ISSUE TITLE
Scale Video

### ISSUE THREAD

**Issue by ch05enOne** [wxxsw/VideoPlayer#37]
Is there any way to scale video properly. My video looks stretched when using the player.

**Comment by milesscherrer** [comment]
Did you solve this?

**Comment by wdnmd123-zzz** [comment]
How to solve this question？

**Comment by wxxsw** [comment]
You can use the contentMode modifier

**Comment by wdnmd123-zzz** [comment]
> 您可以使用内容模式修改器

thanks
