### ISSUE TITLE
Can't start video from specific time

### ISSUE THREAD

**Issue by matanrath40** [wxxsw/VideoPlayer#47]
Hi!
When i'm trying to start the video from specific time, i.e. give the time state a different value other then .zero, the video still starts from the beginning. It seems that the `startObserver` function make it. Is there a way to do it? Thanks!

**Comment by nazar-velkakayev** [comment]
Hi @matanrath40 
how did you solve this problem?

**Comment by GraemeHarrison** [comment]
I'm also struggling with this issue. Any solutions?

**Comment by GraemeHarrison** [comment]
@matanrath40 @nazar-velkakayev I think I found a solution. I created a PR for it [here](https://github.com/wxxsw/VideoPlayer/pull/51).

**Comment by GraemeHarrison** [comment]
The PR above was merged. This issue can be closed now.
