### ISSUE TITLE
Getting current buffer not only when paused

### ISSUE THREAD

**Issue by gasparuff** [wxxsw/VideoPlayer#7]
Hi,

i would like to show the current buffer in % also while the video is playing, how would I do that? 
Thanks!

**Comment by wxxsw** [comment]
Hello, I will try to support it this weekend.

**Comment by wxxsw** [comment]
Added new method `onBufferChanged`, usage example:
```swift
VideoPlayer(url: someVideoURL, play: $play)
    .onBufferChanged { progress in
        // Network loading buffer progress changed
    }
```

**Comment by gasparuff** [comment]
Sorry for the late reply and thank you very much for adding this! :)
