### ISSUE TITLE
How to play video from local file URL?

### ISSUE THREAD

**Issue by ShekharD175** [wxxsw/VideoPlayer#8]

**Comment by wxxsw** [comment]
This is exactly the same as load a web video.
```swift
struct ContentView : View {
    @State private var play: Bool = true
    
    var body: some View {
        VideoPlayer(url: someLocalVideoURL, play: $play)
    }
}
```

**Comment by ShekharD175** [comment]
Tried the above solution already, Not showing the video or frame of Video view

**Comment by ShekharD175** [comment]
I have used like this but not appearing anything on screen, after view debugging able to see video player frame.

"
import SwiftUI
import VideoPlayer

struct PlayVideoView: View {
    
    @State var videoUrl: String
    @State private var play: Bool = true
    
    var body: some View {
                
        VideoPlayer(url: URL(fileURLWithPath: self.videoUrl), play: $play)
        .cornerRadius(15)
        .frame(width: nil, height: 300, alignment: .center)
        .shadow(color: Color.black.opacity(0.7), radius: 30, x: 0, y: 2)
        .padding(.horizontal, 20)
        .padding(.top, 20)
    }
}
"

**Comment by wxxsw** [comment]
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/921863/77839864-607b4f00-71b3-11ea-8d27-3a857933c7c5.png">

**Comment by wxxsw** [comment]
As shown in the screenshot, local videos can be played. But if you still have problems, you can email me the video file and I will test it. （i@gesen.me）
