### ISSUE TITLE
Preloading video preview issue

### ISSUE THREAD

**Issue by hasanals** [wxxsw/VideoPlayer#9]
Hello,
I'm trying to preload the preview of video using VideoPlayer.preload(), it's not working with me. the preview doesn't show

@State var url: URL = URL(string: "https://firebasestorage.googleapis.com/v0/b/mozare3-608bc.appspot.com/o/Jellyfish_0.mp4?alt=media&token=9c808983-db70-4128-bf3e-6d087cc6c601")!

VideoPlayer.preload(urls: [self.url])

Can you please assist me on how to show the preview ?

Thanks,
Hasan

**Comment by wxxsw** [comment]
There is a bug in preloading now. Only when the player is playing, preloading will start.

It is a preload dynamically controlled by VideoPlayer. When the currently playing video buffer is enough, the next video will be preloaded. When the current video buffer is insufficient, the preload will stop.

In addition, VideoPreloadManager does not load the entire video, it only loads the beginning of the video. The main purpose is to enable the preloaded video to play quickly without consuming too much traffic.

If I have time on the weekend, I will try to fix it, and try to provide preloaded strategies such as fast and full download

**Comment by hasanals** [comment]
Thanks for your reply and the effort.
